# SCREEN DIMENSIONS
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800

# COLORS
WHITE = (255, 255, 255)

# FPS LIMIT
FPS = 60

# SPACESHIP (pixels/second)
SPACESHIP_SPEED = 300

# BULLETS
BULLET_SPEED = 250 # (pixels/second)
BULLET_COOLDOWN = 1 # second

# ENEMIES
SPAWN_TIME = 1 # second
ENEMY_SPEED = 50 # (pixels/second)